CREATE TABLE IF NOT EXISTS STOCK_EXCHANGE  (
    id INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(50) NOT NULL,
    LIVE_IN_MARKET BOOLEAN NOT NULL,
    VERSION INT NOT NULL,
    PRIMARY KEY (id));
