spring:
    application:
        name: spring-boot-stock-exchange
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:testdb;
      username: sa
      password:
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      defer-datasource-initialization: true
    sql:
      init:
        data-locations: classpath:db/data.sql
        schema-locations: classpath:db/schema.sql
    h2:
      console:
        enabled: true
        path: /h2-console
